
############################################################
###ADMIN RENDER REQUEST
############################################################
## GET REQUEST
GET https://cse341-finalproject-yq22.onrender.com/admin

###CREAT CONTACT (POST)
POST  https://cse341-finalproject-yq22.onrender.com/admin HTTP/1.1
content-type: application/json

{
    "firstName": "Keeley",
    "lastName": "Imlah",
    "birthday": "na",
    "department": "IT",
    "hireDate": "03/06/2023",
    "level": "1",
    "projectsAssigned": "final project"
}

###UPDATE CONTACT (PUT)
PUT  https://cse341-project2-k61i.onrender.com/admin/640be498a00a16b9a0a5c329 HTTP/1.1
content-type: application/json

{
    "firstName": "Anthony",
    "lastName": "Crew",
    "birthday": "08/08/1988",
    "department": "Estimating",
    "hireDate": "02/10/2010",
    "level": "1",
    "projectsAssigned": "any"
}

###DELETE CONTACT (DELETE)
DELETE   https://cse341-project2-k61i.onrender.com/admin/640aa44ec497d0d4bc1588e7 HTTP/1.1


####################################################################
###EMPLOYEE RENDER REQUEST
####################################################################
##GET REQUEST

GET https://cse341-finalproject-yq22.onrender.com/employee

###CREAT CONTACT (POST)
POST  https://cse341-finalproject-yq22.onrender.com/employee HTTP/1.1
content-type: application/json

{
    "firstName": "Terri",
    "lastName": "Lo",
    "level": "2",
    "projectsAssigned": "final project"
}

##UPDATE CONTACT (PUT)
PUT  https://cse341-project2-k61i.onrender.com/employee/640be582a00a16b9a0a5c32d HTTP/1.1
content-type: application/json

{
    "firstName": "Theo",
    "lastName": "Craven",
    "level": "2",
    "projectsAssigned": "final project"
}

###DELETE CONTACT (DELETE)
DELETE   https://cse341-project2-k61i.onrender.com/employee/640aa480c497d0d4bc1588e8 HTTP/1.1


####################################################################
### EQUIPMENT ###
####################################################################

// POST route for new equipment
POST https://cse341-project2-k61i.onrender.com/equipment HTTP/1.1
content-type: application/json

{
    "equipmentName": "Edger",
    "datePurchased": "10/06/2018",
    "maintenance": [
        "08/17/2020-replaced belt"
    ],
    "available": "false",
    "pastWorkOrders": [
        "348978",
        "111234"
    ],
    "location": "bay 7",
    "notes": ""
}

// GET all equipment
GET https://cse341-project2-k61i.onrender.com/equipment

// GET equipment by id
GET https://cse341-project2-k61i.onrender.com/equipment/64095c3ea4df4c99561e20c6

// PUT for updating equipment based on id
PUT https://cse341-project2-k61i.onrender.com/equipment/64095c3ea4df4c99561e20c8 HTTP/1.1
content-type: application/json

{
    "equipmentName": "Circular Saw",
    "datePurchased": "10/15/2020",
    "maintenance": [
        "07/01/2021-new blade",
        "07/01/2021-lubricate",
        "10/07/2022-new blade"
    ],
    "available": "false",
    "pastWorkOrders": [
        "456789",
        "012356"
    ],
    "location": "1234 job location, City ",
    "notes": "Current job duration: 2.5 weeks"
}

// DELETE by equipment ID
DELETE https://cse341-project2-k61i.onrender.com/equipment HTTP/1.1